#!/usr/bin/env python3
"""Regenerate every artifact in `out/`.

    python examples/run_all.py

Produces, for each of the four cells: a typology report, the crossings as CSV,
the raw typology JSON. Plus a comparison table across all four, an extractor
control report for each corpus that ships with one, a K-D3 run over each, and a
validation report.

Nothing here computes a rate. The demo corpora are fixtures sized to exercise
the instrument, and a rate from a twenty-eight provision fixture would be a
number about the fixture.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rkernel import Chain, generate, load_corpus, load_kernel  # noqa: E402
from rkernel.extract.kd3 import detect  # noqa: E402
from rkernel.extract.norms import extract_norms, summarize  # noqa: E402
from rkernel.extract.ontological import control_report, extract_claims  # noqa: E402
from rkernel.render import (  # noqa: E402
    comparison_markdown,
    crossings_csv,
    report_markdown,
)
from rkernel.typology import compare  # noqa: E402
from rkernel.validate import run_all as validate_all  # noqa: E402

OUT = ROOT / "out"

CELLS = [
    ("frcp", "examples/frcp/frcp.chain.json", "examples/frcp/corpus/frcp_demo.json"),
    ("cfr205", "examples/cfr205/cfr205.chain.json", None),
    ("icd11", "examples/icd11/icd11.chain.json", None),
    ("go", "examples/go/go.chain.json", "examples/go/corpus/go_demo.json"),
]


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"  {path.relative_to(ROOT)}")


def main() -> int:
    kernel = load_kernel()
    typologies = []

    print("typologies")
    for name, chain_path, _ in CELLS:
        chain = Chain.load(ROOT / chain_path)
        typology = generate(chain, kernel)
        typologies.append(typology)
        write(OUT / name / "typology.md", report_markdown(typology, kernel))
        write(OUT / name / "crossings.csv", crossings_csv(typology))
        write(
            OUT / name / "typology.json",
            json.dumps(typology, indent=2, ensure_ascii=False) + "\n",
        )

    print("comparison")
    comparison = compare(typologies)
    write(
        OUT / "comparison.md",
        "# The four cells\n\n"
        "Generated by `examples/run_all.py`. Only the D column varies, and it varies "
        "with chain thickness alone.\n\n"
        + comparison_markdown(comparison, kernel)
        + "\n\nEvery value above is a claim about what **can** occur, not a detection of "
        "what has. See `out/validation.md` for the state of the instrument.\n",
    )

    print("extraction and detection")
    for name, _, corpus_path in CELLS:
        if not corpus_path:
            continue
        provisions, meta = load_corpus(ROOT / corpus_path)
        norms = extract_norms(provisions)
        claims = extract_claims(provisions)
        summary = summarize(norms)
        control = control_report(provisions, summary, claims)
        detection = detect(norms, provisions)

        lines = [
            f"# Extraction: {meta.get('label', name)}",
            "",
            f"**{meta.get('text_status_note', '')}**",
            "",
            "## The within-run control",
            "",
            "| Extractor | Target schema | Yield | Errors |",
            "| --- | --- | --- | --- |",
            f"| Entity-relation | ontological claims | "
            f"{control['entity_relation_extractor']['yield']} | 0 |",
            f"| Norm tuple | deontic norms | {control['norm_tuple_extractor']['yield']} | 0 |",
            "",
            control["reading"],
            "",
            f"By modality: {summary['by_modality']}. "
            f"Duplicates collapsed: {summary['duplicates_collapsed']}.",
            "",
            "## K-D3",
            "",
            f"Capacities examined: {detection['capacities_examined']}. "
            f"Set aside as external: {detection['set_aside_external']}. "
            f"Scored: {detection['scored']}. Candidates: {detection['candidates']}.",
            "",
            "| Fan-out | n | min | median | mean | p90 | max |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            "| pathway matches per capacity | {n} | {min} | {median} | {mean} | {p90} | {max} |".format(
                **detection["fan_out"]
            ),
            "",
            detection["fan_out"]["interpretation"],
            "",
            "Candidates are candidates. Provenance is undetermined on every row, and no "
            "rate computed from a fixture of this size means anything about the source.",
        ]
        write(OUT / name / "extraction.md", "\n".join(lines) + "\n")
        write(
            OUT / name / "detection.json",
            json.dumps(detection, indent=2, ensure_ascii=False) + "\n",
        )

    print("validation")
    report = validate_all()
    write(OUT / "validation.md", report["markdown"] + "\n")

    print("\nok" if report["ok"] else "\nVALIDATION FAILED")
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
